// <auto-generated />
namespace PehliDukaan.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class configCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(configCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "202304132238426_configCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
